<?php
	$num_rows = "82";
	$dbLink = array (
		"1" => array ("Link" => "http://www.sitesell.com/", "Text" => "Achieve life-changing goals"),
		"2" => array ("Link" => "http://buildit.sitesell.com/", "Text" => "Outperform larger competitors"),
		"3" => array ("Link" => "http://bb2.sitesell.com/", "Text" => "BlockBuilder 2 The End of &ldquo;Clunky&rdquo; "),
		"4" => array ("Link" => "http://share.sitesell.com/", "Text" => "Prosperity, Passion, Priorities, Freedom And Family"),
		"5" => array ("Link" => "http://first-day-of-the-rest-of-your-life.sitesell.com/", "Text" => "First Day Of The Rest Of Your Life"),
		"6" => array ("Link" => "http://specialprize.sitesell.com/", "Text" => "Special Free(dom) Prize"),
		"7" => array ("Link" => "http://ilovesbi.sitesell.com/", "Text" => "SBI! Owners Explain How It Changed Their Lives..."),
		"8" => array ("Link" => "http://passion.sitesell.com/", "Text" => "Passion -- For small or home offices, startups, and newbies"),
		"9" => array ("Link" => "http://magic.sitesell.com/", "Text" => "The Magic Page"),
		"10" => array ("Link" => "http://workfromhome.sitesell.com/", "Text" => "Work From Home"),
		"11" => array ("Link" => "http://webhosting.sitesell.com/", "Text" => "Web Hosting"),
		"12" => array ("Link" => "http://videotour.sitesell.com/", "Text" => "The SBI! Video Tour"),
		"13" => array ("Link" => "http://quicktour.sitesell.com/", "Text" => "Quick Tour Slide Show"),
		"14" => array ("Link" => "http://ctpm.sitesell.com/", "Text" => "The 30-Second Nutshell Version of CTPM"),
		"15" => array ("Link" => "http://find.sitesell.com/", "Text" => "Small Business Locator and Idea Finder"),
		"16" => array ("Link" => "http://blogorbuild.sitesell.com/", "Text" => "Should You Blog Or Build A Web Site?"),
		"17" => array ("Link" => "http://wordpress-or-sbi.sitesell.com/", "Text" => "WordPress or SBI!?"),
		"18" => array ("Link" => "http://do-the-math.sitesell.com/", "Text" => "SBI! Or WordPress? Do The Math"),
		"19" => array ("Link" => "http://affiliatemarketing.sitesell.com/", "Text" => "Affiliate Marketers"),
		"20" => array ("Link" => "http://services.sitesell.com/", "Text" => "We Build Websites That Actually Work!"),
		"21" => array ("Link" => "http://adsense.sitesell.com/", "Text" => "Google AdSense And SBI!..."),
		"22" => array ("Link" => "http://auctions.sitesell.com/", "Text" => "Online Auction Sellers"),
		"23" => array ("Link" => "http://egoods.sitesell.com/", "Text" => "Selling E-goods"),
		"24" => array ("Link" => "http://traffic.sitesell.com/", "Text" => "Let Your Visitors Take The Traffic Test"),
		"25" => array ("Link" => "http://hardgoods.sitesell.com/", "Text" => "Selling Hard Goods"),
		"26" => array ("Link" => "http://infopublishing.sitesell.com/", "Text" => "InfoPublishing, For The Aspiring Infopreneur"),
		"27" => array ("Link" => "http://localbiz.sitesell.com/", "Text" => "For LOCAL Businesses with LOCAL Clients"),
		"28" => array ("Link" => "http://networkmarketing.sitesell.com/", "Text" => "Network Marketers"),
		"29" => array ("Link" => "http://realestate.sitesell.com/", "Text" => "Real Estate"),
		"30" => array ("Link" => "http://findersfee.sitesell.com/", "Text" => "Referrers/Finders"),
		"31" => array ("Link" => "http://sales-rentals.sitesell.com/", "Text" => "Sales/Rental Agents"),
		"32" => array ("Link" => "http://service-selling.sitesell.com/", "Text" => "For Those Selling a Service... or Could Be!"),
		"33" => array ("Link" => "http://travel.sitesell.com/", "Text" => "Travel Means Business"),
		"34" => array ("Link" => "http://webmaster.sitesell.com/", "Text" => "Professional Webmasters Are Catching On"),
		"35" => array ("Link" => "http://retire.sitesell.com/", "Text" => "Retirees/Pre-Retirees"),
		"36" => array ("Link" => "http://students.sitesell.com/", "Text" => "University Students"),
		"37" => array ("Link" => "http://wahm.sitesell.com/", "Text" => "WAHMs, &ldquo;Work At Home Moms&rdquo; "),
		"38" => array ("Link" => "http://case-studies.sitesell.com/", "Text" => "The biggest mistake people make"),
		"39" => array ("Link" => "http://urbanmyths.sitesell.com/", "Text" => "Build a worldwide reputation"),
		"40" => array ("Link" => "http://services-casestudies.sitesell.com/", "Text" => "SiteSell Services Builds eBusinesses..."),
		"41" => array ("Link" => "http://course.sitesell.com/", "Text" => "Online Self-Study E-business Course"),
		"42" => array ("Link" => "http://samples.sitesell.com/", "Text" => "Real World Samples"),
		"43" => array ("Link" => "http://results.sitesell.com/", "Text" => "Want Results?"),
		"44" => array ("Link" => "http://compare.sitesell.com/", "Text" => "Compare Dollar-For-Dollar"),
		"45" => array ("Link" => "http://action-guide.sitesell.com/", "Text" => "Action Guide"),
		"46" => array ("Link" => "http://demo.sitesell.com/", "Text" => "Action Guide Video"),
		"47" => array ("Link" => "http://aff-masters.sitesell.com/", "Text" => "Affiliate Masters Course"),
		"48" => array ("Link" => "http://affiliates.sitesell.com/", "Text" => "Affiliates 5P"),
		"49" => array ("Link" => "http://traffic-test.sitesell.com/", "Text" => "Alexa Point Traffic Test"),
		"50" => array ("Link" => "http://chooseit.sitesell.com/", "Text" => "Choose It!"),
		"51" => array ("Link" => "http://local-biz-masters.sitesell.com/", "Text" => "Local Business Masters Course"),
		"52" => array ("Link" => "http://longtail.sitesell.com/", "Text" => "Long Tail Marketing"),
		"53" => array ("Link" => "http://mycps.sitesell.com/", "Text" => "Make Your Content PREsell!"),
		"54" => array ("Link" => "http://myks.sitesell.com/", "Text" => "Make Your Knowledge Sell!"),
		"55" => array ("Link" => "http://value-exchange.sitesell.com/", "Text" => "Make Your Links WORK!"),
		"56" => array ("Link" => "http://mynas.sitesell.com/", "Text" => "Make Your Net Auction Sell!"),
		"57" => array ("Link" => "http://mynas-masters.sitesell.com/", "Text" => "Make Your Net Auction Sell!, The Masters Course"),
		"58" => array ("Link" => "http://myps.sitesell.com/", "Text" => "Make Your Price Sell!"),
		"59" => array ("Link" => "http://myps-masters.sitesell.com/", "Text" => "Make Your Price Sell!, The Masters Course"),
		"60" => array ("Link" => "http://myss.sitesell.com/", "Text" => "Make Your Site Sell!"),
		"61" => array ("Link" => "http://myws.sitesell.com/", "Text" => "Make Your Words Sell!"),
		"62" => array ("Link" => "http://media.sitesell.com/", "Text" => "The media is the toughest audience there is"),
		"63" => array ("Link" => "http://netwriting.sitesell.com/", "Text" => "Netwriting Masters Course"),
		"64" => array ("Link" => "http://proof.sitesell.com/", "Text" => "It/'s About Success."),
		"65" => array ("Link" => "http://question.sitesell.com/", "Text" => "How Can SBI! Work For You?"),
		"66" => array ("Link" => "http://seminars.sitesell.com/", "Text" => "How Can the Web Help My Business?"),
		"67" => array ("Link" => "http://retire.sitesell.com/", "Text" => "Retired? Getting Close? What Will You Retire To?"),
		"68" => array ("Link" => "http://tools.sitesell.com/", "Text" => "All the Tools, All in One Place"),
		"69" => array ("Link" => "http://sbi2-4u.sitesell.com/", "Text" => "The Only Complete E-business Builder"),
		"70" => array ("Link" => "http://2.sitesell.com/", "Text" => "Imagine Visitors Building Your Business... For Free..."),
		"71" => array ("Link" => "http://order.sitesell.com/", "Text" => "Take Full Advantage Of The 90 Day Guarantee A Risk-Free Trial."),
		"72" => array ("Link" => "http://searchit.sitesell.com/", "Text" => "Your Power-Searching E-Business Tool"),
		"73" => array ("Link" => "http://service-masters.sitesell.com/", "Text" => "Service Sellers Masters Course"),
		"74" => array ("Link" => "http://blogit.sitesell.com/", "Text" => "SiteSell Blog"),
		"75" => array ("Link" => "http://facebook.sitesell.com/", "Text" => "SiteSell Facebook"),
		"76" => array ("Link" => "http://freetrial.sitesell.com/", "Text" => "SiteSell Free Downloads"),
		"77" => array ("Link" => "http://twitter.sitesell.com/", "Text" => "SiteSell Twitter"),
		"78" => array ("Link" => "http://youtube.sitesell.com/", "Text" => "SiteSell YouTube"),
		"79" => array ("Link" => "http://spamcheck.sitesell.com/", "Text" => "SpamCheck"),
		"80" => array ("Link" => "http://6thpillar.sitesell.com/", "Text" => "The best way to get a Jump Start"),
		"81" => array ("Link" => "http://wahm-masters.sitesell.com/", "Text" => "WAHM-IT!, The Masters Course"),
		"82" => array ("Link" => "http://webmasterbusiness.sitesell.com/", "Text" => "Webmaster BUSINESS Masters Course")
		);				
?>